server:
  port: 8008

spring:
  application:
    name: zhifu-openFeign-jiekou-8008
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
ribbon:
  #读取时间
  ReadTimeout:  6000
  #连接时间
  ConnectTimeout: 6000
logging:
  level:
    com.cloud1.PayService.PayMentService: debug


feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000